version: "3"
services:
  lnmp:
    build: .
    container_name: lnmp
    ports:
      - 8081:80
      - 8082:8000
    volumes:
      - ${WORK_DIR}:/var/www
    working_dir: /var/www
    user: "${UID}:${GID}"
    restart: always
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
#    command: [ "/usr/local/bin/php", "/var/www/my-project/la8/artisan", "octane:start", "--watch", "--host=0.0.0.0" ]
  debian:
    image: debian:bullseye
    container_name: debian
    tty: true