version: "3"
services:
  lnmp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
        - USER=lnmp-user
        - GROUP=lnmp-group
    container_name: lnmp
    ports:
      - 8081:80
      - 8082:8000
    volumes:
      - ${WORK_DIR}:/var/www
    working_dir: /var/www
    user: "${UID}:${GID}"
    restart: always
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  debian:
    image: debian:bullseye
    container_name: debian
    tty: true